### ISSUE TITLE
jfa-go segfaults repeatedly after initial setup

### ISSUE THREAD

**Issue by divisini** [hrfee/jfa-go#124]
**Description:**
Constant, looping segfaults after going thru initial setup. Occurs on :latest and :unstable tags.

**Reproduction:**
Add jfa-go to a compose file, go thru initial setup with confirmed functional Jellyfin and Ombi installations, and...that's it.

```yaml
  jfa-go:
     image: hrfee/jfa-go:unstable  
     container_name: jfacct  
     user: 2014:2001  
     networks:  
       - frontend  
       - backend_media  
     environment:  
       - UID=2014  
       - GID=2001  
     ports:  
       - 8056:8056  
     volumes:  
       - /opt/jfacct:/data  
       - /opt/jellyfin:/jf  
       - /etc/localtime:/etc/localtime:ro  
     depends_on:  
       - "jellyfin"  
     restart: unless-stopped  
```

**Logs**
```
docker-compose[115060]: jfacct            | 2021/06/26 09:35:59 Using external storage
docker-compose[115060]: jfacct            | jfa-go version: git (21b373a)
docker-compose[115060]: jfacct            |
docker-compose[115060]: jfacct            | Socket: /tmp/jfa-go.sock
docker-compose[115060]: jfacct            | [INFO] 09:35:59  Using Jellyfin server type
docker-compose[115060]: jfacct            | panic: runtime error: invalid memory address or nil pointer dereference
docker-compose[115060]: jfacct            | [signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x6bb48e]
docker-compose[115060]: jfacct            |
docker-compose[115060]: jfacct            | goroutine 1 [running]:
docker-compose[115060]: jfacct            | net/http.(*Client).do(0xc0004eede0, 0x0, 0x0, 0x0, 0x0)
docker-compose[115060]: jfacct            |         /usr/local/go/src/net/http/client.go:594 +0xae
docker-compose[115060]: jfacct            | net/http.(*Client).Do(...)
docker-compose[115060]: jfacct            |         /usr/local/go/src/net/http/client.go:585
docker-compose[115060]: jfacct            | github.com/hrfee/mediabrowser.NewServer(0x0, 0xc0002942b9, 0x10, 0xc00028a189, 0x6, 0>
docker-compose[115060]: jfacct            |         /go/pkg/mod/github.com/hrfee/mediabrowser@v0.3.3/mediabrowser.go:110 +0x78c
docker-compose[115060]: jfacct            | main.start(0xc70100)
docker-compose[115060]: jfacct            |         /opt/build/main.go:430 +0x2285
docker-compose[115060]: jfacct            | main.main()
docker-compose[115060]: jfacct            |         /opt/build/main.go:836 +0x785
docker-compose[115060]: jfacct exited with code 2
```

**Platform/Version**

jfa-go ```git:21b373a```
Docker ```20.10.7```
compose ```1.29.2```
Host: ```Arch Linux```
