### ISSUE TITLE
Addition - Traefik reverse proxy with Password reset

### ISSUE THREAD

**Issue by aleksasiriski** [hrfee/jfa-go#232]
Config for traefik reverse proxy with the fix for resetting password outside local network:

```
jellyfin:
    image: jellyfin/jellyfin:latest
    environment:
      - TZ=Europe/Berlin
      - JELLYFIN_PublishedServerUrl=https://jellyfin.$ROOT_DOMAIN
    volumes:
      - jellyfin-conf:/config:Z
      - jellyfin-cache:/cache:Z
    restart: always
    labels:
      - "traefik.http.middlewares.forgot-password-forwarded.headers.customrequestheaders.X-Forwarded-For=127.0.0.1"
      - "traefik.http.middlewares.forgot-password-real.headers.customrequestheaders.X-Real-Ip=127.0.0.1"
      - "traefik.http.routers.jellyfin.rule=Host(`jellyfin.$ROOT_DOMAIN`)"
      - "traefik.http.routers.jellyfin-forgot-password.rule=Host(`jellyfin.$ROOT_DOMAIN`) && (Path(`/Users/ForgotPassword`) || Path(`/Users/ForgotPassword/Pin`))"
      - "traefik.http.routers.jellyfin-forgot-password.middlewares=forgot-password-forwarded@docker,forgot-password-real@docker"
```
