### ISSUE TITLE
Traefik reverse proxy fails when using base URL

### ISSUE THREAD

**Issue by MrLemur** [hrfee/jfa-go#53]
#### Read the [FAQ](https://github.com/hrfee/jfa-go/wiki/FAQ) first!

**Describe the bug**

Traefik reverse proxy fails if `url_base` set. Works fine on a subdomain, but will show 404 when on a base URL. The page constantly tries to access `css/*` etc in a loop when loaded.

![image](https://user-images.githubusercontent.com/17055328/107675897-750feb00-6c90-11eb-8a5c-62b02de53ea9.png)
![image](https://user-images.githubusercontent.com/17055328/107675936-7f31e980-6c90-11eb-822f-9bd5f3c68bb9.png)

**To Reproduce**

What to do to reproduce the problem.

**Logs**

```
jfa-go_1         | [GIN/DEBUG] 17:44:33: GET(/jfa/css/remixicon.css) => 404 in 15.106287ms; 
jfa-go_1         | [GIN/DEBUG] 17:44:33: GET(/jfa/css/bundle.css) => 404 in 4.464636ms; 
jfa-go_1         | [GIN/DEBUG] 17:44:33: GET(/jfa/css/remixicon.css) => 404 in 4.170007ms; 
jfa-go_1         | [GIN/DEBUG] 17:44:33: GET(/jfa/css/bundle.css) => 404 in 4.261646ms; 
jfa-go_1         | [GIN/DEBUG] 17:44:33: GET(/jfa/css/remixicon.css) => 404 in 3.39886ms; 
jfa-go_1         | [GIN/DEBUG] 17:44:33: GET(/jfa/css/bundle.css) => 404 in 4.219146ms; 
jfa-go_1         | [GIN/DEBUG] 17:44:33: GET(/jfa/css/remixicon.css) => 404 in 3.291027ms; 
jfa-go_1         | [GIN/DEBUG] 17:44:33: GET(/jfa/css/bundle.css) => 404 in 3.163965ms; 
jfa-go_1         | [GIN/DEBUG] 17:44:33: GET(/jfa/css/remixicon.css) => 404 in 3.461112ms; 
jfa-go_1         | [GIN/DEBUG] 17:44:33: GET(/jfa/css/bundle.css) => 404 in 3.266258ms; 
jfa-go_1         | [GIN/DEBUG] 17:44:33: GET(/jfa/css/remixicon.css) => 404 in 3.411234ms; 
jfa-go_1         | [GIN/DEBUG] 17:44:33: GET(/jfa/css/bundle.css) => 404 in 3.760947ms; 
jfa-go_1         | [GIN/DEBUG] 17:44:33: GET(/jfa/css/remixicon.css) => 404 in 3.579617ms; 
jfa-go_1         | [GIN/DEBUG] 17:44:33: GET(/jfa/css/bundle.css) => 404 in 3.373669ms; 
jfa-go_1         | [GIN/DEBUG] 17:44:33: GET(/jfa/css/remixicon.css) => 404 in 3.285983ms; 
jfa-go_1         | [GIN/DEBUG] 17:44:33: GET(/jfa/css/bundle.css) => 404 in 3.738771ms; 
```

**Configuration**

url_base set to `/jfa`

docker config:

```
jfa-go:
    image: hrfee/jfa-go:unstable
    restart: always
    user: 1000:1000
    volumes:
      - /opt/docker/jfa-go:/data
      - /opt/docker/jellyfin:/jf
      - /etc/localtime:/etc/localtime:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.jfa-go.rule=Host(`services.${DOMAIN}`) && PathPrefix(`/jfa`)"
      - "traefik.http.routers.jfa-go.tls=true"
```

**Platform/Version**

Docker, latest git as of 11/02/2021 17:30 GMT

**Comment by hrfee** [comment]
The URL has to be rewritten to remove `/jfa`, with nginx i use 
`rewrite ^/jfa/(.*) /$1 break;`. 
Apparently `PathPrefixStrip: /jfa` would be equivalent in traefik, although i don't know where you would put this.

**Comment by MrLemur** [comment]
Okay that makes sense. I assume the server in go won't change the directory to serve requests from based on the `url_base` value?

**Comment by hrfee** [comment]
No, it doesn't but that probably would have been a better design choice.

**Comment by MrLemur** [comment]
I now have it working correctly with Traefik if anyone else runs into the issue:

```
  jfa-go:
    image: hrfee/jfa-go:unstable
    restart: always
    user: 1000:1000
    volumes:
      - /opt/docker/jfa-go:/data
      - /opt/docker/jellyfin:/jf
      - /etc/localtime:/etc/localtime:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.jfa-go.rule=Host(`services.${DOMAIN}`) && PathPrefix(`/jfa`)"
      - "traefik.http.middlewares.jfa-go-strip.stripprefix.prefixes=/jfa"
      - "traefik.http.routers.jfa-go.tls=true"
      - "traefik.http.routers.jfa-go.middlewares=jfa-go-strip@docker"
```
